Handling Collections Callable Attribute missing issue in 3.9+
In python 3.11, when working on a module, I got below error. 
\pyreadline\py3k_compat.py", line 8, in callable    return isinstance(x, collections.Callable)
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'

When researched I understood that Collections module was modified. It moved collections.Callable to collections.abc.Callable
Handled that change, bearing in mind backward compatibility